### ISSUE TITLE
Ignored Files Still Run

### ISSUE THREAD

**Issue by saulshanabrook** [weavejester/codox#100]
I have a few files that shouldn't be looked at by codox, because when it accesses them they start processes or have raise errors, based on mutations of global state.

I tried adding `:exclude #".*"`, which did work in stopping codox from generating any docs, but it still seemed to read all the files. 

```bash
root@c4afb62ebc57:/usr/src/app# lein doc
Could not generate clojure documentation for clojush.problems.boolean.mux-6 - root cause: clojure.lang.Compiler$CompilerException java.lang.Exception: Duplicate Push instruction defined:a0, compiling:(clojush/problems/boolean/mux_6.clj:40:1)
java.lang.Exception: Duplicate Push instruction defined:a0, compiling:(clojush/problems/boolean/mux_6.clj:40:1)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at codox.reader.clojure$read_ns.invoke(clojure.clj:67)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:674)
	at clojure.core$next__4112.invoke(core.clj:64)
	at clojure.core$concat$cat__4217$fn__4218.invoke(core.clj:707)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:507)
	at clojure.core$seq__4128.invoke(core.clj:137)
	at clojure.core$filter$fn__4580.invoke(core.clj:2679)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
[...truncated output...]
Generated HTML docs in /usr/src/app/doc
root@c4afb62ebc57:/usr/src/app# ls doc/
css  index.html  js
```

Is it possible to tell codox not to even read some files?

**Comment by weavejester** [comment]
> I have a few files that shouldn't be looked at by codox, because when it accesses them they start processes or have raise errors, based on mutations of global state.

Ideally, loading a Clojure namespace shouldn't produce any additional side effects.

That said, there's no point in reading source files if they're going to be excluded anyway, so this seems a reasonable change to make.

**Comment by saulshanabrook** [comment]
Yeah I agree, in an ideal world this wouldn't produce side effects. Would it be difficult to not read any files that are ignored/

**Comment by weavejester** [comment]
On the other hand, we don't know for sure what namespaces are in files until they've read. I guess just reading the ns declaration might be enough under most circumstances.

**Comment by saulshanabrook** [comment]
Oh yeah, I see what you mean. Or, if we could exclude based on file path, that would also work.

**Comment by saulshanabrook** [comment]
@weavejester Any progress on this in `0.9.0`?

**Comment by weavejester** [comment]
No-one's submitted any PRs for this yet, I'm afraid.
