### ISSUE TITLE
core.async breaks codox 0.8.14

### ISSUE THREAD

**Issue by puppe** [weavejester/codox#101]
## Problem

When I execute `lein doc`, I get the following error:

```
Exception in thread "main" java.lang.Exception: Could not load codox writer codox.writer.html, compiling:(/private/var/folders/cn/6_qzyn2n0bqc880m3cd9vht40000gn/T/form-init4593983510146394534.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Could not load codox writer codox.writer.html
	at codox.main$writer$fn__545.invoke(main.clj:13)
	at codox.main$writer.invoke(main.clj:9)
	at codox.main$generate_docs.invoke(main.clj:74)
	at user$eval609.invoke(form-init4593983510146394534.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException, compiling:(html.clj:30:1)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:452)
	at clojure.lang.Compiler.eval(Compiler.java:6787)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at codox.main$writer$fn__545.invoke(main.clj:10)
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at clojure.lang.Compiler$NewExpr.eval(Compiler.java:2553)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:439)
	... 37 more
Caused by: java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:94)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:73)
	... 43 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.objectweb.asm.MethodVisitor.<init>(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.<init>(Unknown Source)
	at org.objectweb.asm.tree.MethodNode.<init>(Unknown Source)
	at org.parboiled.transform.ClassNodeInitializer.visitMethod(ClassNodeInitializer.java:136)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:63)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:44)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	... 45 more
Subprocess failed
```

## Steps to reproduce

1. `lein new example`
2. `cd example`
3. Add `[org.clojure/core.async "0.1.346.0-17112a-alpha"]` to
   dependencies.
4. `lein doc`

It works fine, if I either use codox 0.8.13, or if I remove the
dependency on core.async.

### project.clj

``` clojure
(defproject example "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :plugins [[codox "0.8.14"]]
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]])
```

**Comment by weavejester** [comment]
It looks like you're running into a dependency problem. Both Pegdown and core.async use ASM, a bytecode manipulation library. The problem is that Pegdown uses version 5.0.3, while core.async uses version 4.1.

Adding the following dependency to the project appears to fix the issue without causing any problems for core.async (at least none that I could detect):

```clojure
[org.ow2.asm/asm-all "5.0.3"]
```

I can also add this dependency to Codox itself, but the problem with Leiningen/Maven dependencies is that they don't go for the latest dependency, but the *nearest* one to the project. So while adding the dependency to Codox would solve most issues, there will always be corner cases where you just need to fix the dependencies manually.

**Comment by weavejester** [comment]
Also, thanks for the report :)

**Comment by puppe** [comment]
Thanks for the quick fix! :)
