### ISSUE TITLE
Exception: Unable to resolve symbol: ->MapDependencyGraph in this context

### ISSUE THREAD

**Issue by boechat107** [weavejester/codox#105]
Using `[lein-codox "0.9.0"]` and a fresh clone of [enlive](https://github.com/cgrand/enlive), the API generation failed with the following stacktrace:

```
▶ lein codox
Exception in thread "main" java.lang.Exception: Unable to resolve symbol: ->MapDependencyGraph in this context (dependency.clj:108)
        at clojure.lang.Compiler.analyze(Compiler.java:5205)
        at clojure.lang.Compiler.analyze(Compiler.java:5151)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3036)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:5371)
        at clojure.lang.Compiler.analyze(Compiler.java:5190)
        at clojure.lang.Compiler.analyze(Compiler.java:5151)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:4670)
        at clojure.lang.Compiler$FnMethod.parse(Compiler.java:4328)
        at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3173)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:5367)
        at clojure.lang.Compiler.analyze(Compiler.java:5190)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:5357)
        at clojure.lang.Compiler.analyze(Compiler.java:5190)
        at clojure.lang.Compiler.analyze(Compiler.java:5151)
        at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:798)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:5369)
        at clojure.lang.Compiler.analyze(Compiler.java:5190)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:5357)
        at clojure.lang.Compiler.analyze(Compiler.java:5190)
        at clojure.lang.Compiler.access$100(Compiler.java:35)
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:438)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:5369)
        at clojure.lang.Compiler.analyze(Compiler.java:5190)
        at clojure.lang.Compiler.analyze(Compiler.java:5151)
        at clojure.lang.Compiler.eval(Compiler.java:5428)
        at clojure.lang.Compiler.load(Compiler.java:5857)
        at clojure.lang.RT.loadResourceScript(RT.java:340)
        at clojure.lang.RT.loadResourceScript(RT.java:331)
        at clojure.lang.RT.load(RT.java:409)
        at clojure.lang.RT.load(RT.java:381)
        at clojure.core$load$fn__4511.invoke(core.clj:4905)
        at clojure.core$load.doInvoke(core.clj:4904)
        at clojure.lang.RestFn.invoke(RestFn.java:409)
        at clojure.core$load_one.invoke(core.clj:4729)
        at clojure.core$load_lib.doInvoke(core.clj:4766)
        at clojure.lang.RestFn.applyTo(RestFn.java:143)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$load_libs.doInvoke(core.clj:4800)
        at clojure.lang.RestFn.applyTo(RestFn.java:138)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$require.doInvoke(core.clj:4869)
        at clojure.lang.RestFn.invoke(RestFn.java:422)
        at clojure.tools.namespace.track$eval164$loading__4410__auto____165.invoke(track.clj:9)
        at clojure.tools.namespace.track$eval164.invoke(track.clj:9)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        at clojure.lang.Compiler.eval(Compiler.java:5415)
        at clojure.lang.Compiler.load(Compiler.java:5857)
        at clojure.lang.RT.loadResourceScript(RT.java:340)
        at clojure.lang.RT.loadResourceScript(RT.java:331)
        at clojure.lang.RT.load(RT.java:409)
        at clojure.lang.RT.load(RT.java:381)
        at clojure.core$load$fn__4511.invoke(core.clj:4905)
        at clojure.core$load.doInvoke(core.clj:4904)
        at clojure.lang.RestFn.invoke(RestFn.java:409)
        at clojure.core$load_one.invoke(core.clj:4729)
        at clojure.core$load_lib.doInvoke(core.clj:4766)
        at clojure.lang.RestFn.applyTo(RestFn.java:143)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$load_libs.doInvoke(core.clj:4800)
        at clojure.lang.RestFn.applyTo(RestFn.java:138)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$require.doInvoke(core.clj:4869)
        at clojure.lang.RestFn.invoke(RestFn.java:437)
        at clojure.tools.namespace.file$eval128$loading__4410__auto____129.invoke(file.clj:9)
        at clojure.tools.namespace.file$eval128.invoke(file.clj:9)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        at clojure.lang.Compiler.eval(Compiler.java:5415)
        at clojure.lang.Compiler.load(Compiler.java:5857)
        at clojure.lang.RT.loadResourceScript(RT.java:340)
        at clojure.lang.RT.loadResourceScript(RT.java:331)
        at clojure.lang.RT.load(RT.java:409)
        at clojure.lang.RT.load(RT.java:381)
        at clojure.core$load$fn__4511.invoke(core.clj:4905)
        at clojure.core$load.doInvoke(core.clj:4904)
        at clojure.lang.RestFn.invoke(RestFn.java:409)
        at clojure.core$load_one.invoke(core.clj:4729)
        at clojure.core$load_lib.doInvoke(core.clj:4766)
        at clojure.lang.RestFn.applyTo(RestFn.java:143)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$load_libs.doInvoke(core.clj:4800)
        at clojure.lang.RestFn.applyTo(RestFn.java:138)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$require.doInvoke(core.clj:4869)
        at clojure.lang.RestFn.invoke(RestFn.java:458)
        at clojure.tools.namespace.find$eval122$loading__4410__auto____123.invoke(find.clj:9)
        at clojure.tools.namespace.find$eval122.invoke(find.clj:9)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        at clojure.lang.Compiler.eval(Compiler.java:5415)
        at clojure.lang.Compiler.load(Compiler.java:5857)
        at clojure.lang.RT.loadResourceScript(RT.java:340)
        at clojure.lang.RT.loadResourceScript(RT.java:331)
        at clojure.lang.RT.load(RT.java:409)
        at clojure.lang.RT.load(RT.java:381)
        at clojure.core$load$fn__4511.invoke(core.clj:4905)
        at clojure.core$load.doInvoke(core.clj:4904)
        at clojure.lang.RestFn.invoke(RestFn.java:409)
        at clojure.core$load_one.invoke(core.clj:4729)
        at clojure.core$load_lib.doInvoke(core.clj:4766)
        at clojure.lang.RestFn.applyTo(RestFn.java:143)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$load_libs.doInvoke(core.clj:4800)
        at clojure.lang.RestFn.applyTo(RestFn.java:138)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$require.doInvoke(core.clj:4869)
        at clojure.lang.RestFn.invoke(RestFn.java:437)
        at codox.reader.clojure$eval116$loading__4410__auto____117.invoke(clojure.clj:1)
        at codox.reader.clojure$eval116.invoke(clojure.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        at clojure.lang.Compiler.eval(Compiler.java:5415)
        at clojure.lang.Compiler.load(Compiler.java:5857)
        at clojure.lang.RT.loadResourceScript(RT.java:340)
        at clojure.lang.RT.loadResourceScript(RT.java:331)
        at clojure.lang.RT.load(RT.java:409)
        at clojure.lang.RT.load(RT.java:381)
        at clojure.core$load$fn__4511.invoke(core.clj:4905)
        at clojure.core$load.doInvoke(core.clj:4904)
        at clojure.lang.RestFn.invoke(RestFn.java:409)
        at clojure.core$load_one.invoke(core.clj:4729)
        at clojure.core$load_lib.doInvoke(core.clj:4766)
        at clojure.lang.RestFn.applyTo(RestFn.java:143)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$load_libs.doInvoke(core.clj:4800)
        at clojure.lang.RestFn.applyTo(RestFn.java:138)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$require.doInvoke(core.clj:4869)
        at clojure.lang.RestFn.invoke(RestFn.java:422)
        at codox.main$eval9$loading__4410__auto____10.invoke(main.clj:1)
        at codox.main$eval9.invoke(main.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        at clojure.lang.Compiler.eval(Compiler.java:5415)
        at clojure.lang.Compiler.load(Compiler.java:5857)
        at clojure.lang.RT.loadResourceScript(RT.java:340)
        at clojure.lang.RT.loadResourceScript(RT.java:331)
        at clojure.lang.RT.load(RT.java:409)
        at clojure.lang.RT.load(RT.java:381)
        at clojure.core$load$fn__4511.invoke(core.clj:4905)
        at clojure.core$load.doInvoke(core.clj:4904)
        at clojure.lang.RestFn.invoke(RestFn.java:409)
        at clojure.core$load_one.invoke(core.clj:4729)
        at clojure.core$load_lib.doInvoke(core.clj:4766)
        at clojure.lang.RestFn.applyTo(RestFn.java:143)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$load_libs.doInvoke(core.clj:4800)
        at clojure.lang.RestFn.applyTo(RestFn.java:138)
        at clojure.core$apply.invoke(core.clj:542)
        at clojure.core$require.doInvoke(core.clj:4869)
        at clojure.lang.RestFn.invoke(RestFn.java:409)
        at user$eval5.invoke(form-init2804375145063593124.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:5424)
        at clojure.lang.Compiler.eval(Compiler.java:5414)
        at clojure.lang.Compiler.load(Compiler.java:5857)
        at clojure.lang.Compiler.loadFile(Compiler.java:5820)
        at clojure.main$load_script.invoke(main.clj:221)
        at clojure.main$init_opt.invoke(main.clj:226)
        at clojure.main$initialize.invoke(main.clj:254)
        at clojure.main$null_opt.invoke(main.clj:279)
        at clojure.main$main.doInvoke(main.clj:354)
        at clojure.lang.RestFn.invoke(RestFn.java:422)
        at clojure.lang.Var.invoke(Var.java:369)
        at clojure.lang.AFn.applyToHelper(AFn.java:165)
        at clojure.lang.Var.applyTo(Var.java:482)
        at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Unable to resolve symbol: ->MapDependencyGraph in this context
        at clojure.lang.Compiler.resolveIn(Compiler.java:5677)
        at clojure.lang.Compiler.resolve(Compiler.java:5621)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:5584)
        at clojure.lang.Compiler.analyze(Compiler.java:5172)
        ... 161 more
Subprocess failed
```

**Comment by weavejester** [comment]
Enlive has a Clojure dependency of 1.2.0. Codox doesn't support Clojure versions older than 1.3.0. If you update the Clojure dependency in Enlive to 1.3.0, then it should work.

**Comment by boechat107** [comment]
Perfect!!  =)

Thanks, @weavejester!
