### ISSUE TITLE
NullPointerException when generating docs

### ISSUE THREAD

**Issue by ssuehs-shango** [weavejester/codox#116]
Problem is with lein-codox 0.9.3, does not happen with lein-codox 0.9.2.

```````
 lein codox  
Retrieving lein-codox/lein-codox/0.9.3/lein-codox-0.9.3.pom from clojars
Retrieving lein-codox/lein-codox/0.9.3/lein-codox-0.9.3.jar from clojars
Retrieving codox/codox/0.9.3/codox-0.9.3.pom from clojars
Retrieving org/clojure/tools.namespace/0.2.11/tools.namespace-0.2.11.pom from central
Retrieving org/clojure/clojurescript/1.7.189/clojurescript-1.7.189.pom from central
Retrieving enlive/enlive/1.1.6/enlive-1.1.6.pom from clojars
Retrieving org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.pom from central
Retrieving org/pegdown/pegdown/1.6.0/pegdown-1.6.0.pom from central
Retrieving org/parboiled/parboiled-java/1.1.7/parboiled-java-1.1.7.pom from central
Retrieving org/parboiled/parboiled-core/1.1.7/parboiled-core-1.1.7.pom from central
Retrieving org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.pom from central
Retrieving org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.pom from central
Retrieving org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.pom from central
Retrieving org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.pom from central
Retrieving org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar from central
Retrieving org/clojure/tools.namespace/0.2.11/tools.namespace-0.2.11.jar from central
Retrieving org/pegdown/pegdown/1.6.0/pegdown-1.6.0.jar from central
Retrieving org/parboiled/parboiled-java/1.1.7/parboiled-java-1.1.7.jar from central
Retrieving org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar from central
Retrieving org/parboiled/parboiled-core/1.1.7/parboiled-core-1.1.7.jar from central
Retrieving org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar from central
Retrieving org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar from central
Retrieving org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar from central
Retrieving codox/codox/0.9.3/codox-0.9.3.jar from clojars
Retrieving enlive/enlive/1.1.6/enlive-1.1.6.jar from clojars
Exception in thread "main" java.lang.NullPointerException, compiling:(/tmp/form-init373578296055441984.clj:1:72)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
	at codox.writer.html$add_ending.invoke(html.clj:280)
	at codox.writer.html$index_page.invoke(html.clj:292)
	at codox.writer.html$write_index.invoke(html.clj:392)
	at codox.writer.html$write_docs.invoke(html.clj:407)
	at clojure.lang.Var.invoke(Var.java:379)
	at codox.main$generate_docs.invoke(main.clj:94)
	at user$eval638.invoke(form-init373578296055441984.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Subprocess failed
``````````````

**Comment by weavejester** [comment]
What does your project file look like? Is it missing a `:description` key?

**Comment by ssuehs-shango** [comment]
It does lack a :description key.  

```````
(defproject hello-seymore "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.170"]
                 [sablono "0.3.6"]
                 [cljsjs/moment "2.10.6-1"]
                 [rm-hull/monet "0.2.2"]]
  :plugins [[lein-figwheel "0.5.0-1"]]
  :clean-targets [:target-path "out"]
  :cljsbuild {
    :builds [{:id "dev"
              :source-paths ["src"]
              :figwheel true
              :compiler {:main "hello-world.core"}
             }]
   })
```````

I shall add one and try again.

**Comment by ssuehs-shango** [comment]
That did it.  The documentation is empty but I suspect that is a cljs issue.  Thank you.  I wonder if I missed something when I read the fine README.

**Comment by weavejester** [comment]
Reopening, because Codox shouldn't except when there isn't a description.

**Comment by ssuehs-shango** [comment]
Thank you!
