### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by mbossenbroek** [weavejester/codox#127]
I just updated codox to the latest release, and I'm getting the following exception when I try to run it.

I'm trying to create docs for pigpen (https://github.com/Netflix/PigPen) using this project.clj file: https://gist.github.com/mbossenbroek/24d3a0ec41aa1d1381b48f988c94c815

It looks like a dependency mismatch, but I don't know how to ask leiningen to describe the dependencies for a plugin.

```
$ lein do clean, codox
Compiling 12 source files to /Users/mbossenbroek/src/pigpen/target/classes
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Exception in thread "main" java.lang.Exception: Could not load codox writer codox.writer.html, compiling:(/private/var/folders/67/j3cmftz165780yl4p2zx9t540000gp/T/form-init3270266102980636870.clj:1:124)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Could not load codox writer codox.writer.html
	at codox.main$writer$fn__571.invoke(main.clj:14)
	at codox.main$writer.invoke(main.clj:10)
	at codox.main$generate_docs.invoke(main.clj:91)
	at user$eval646.invoke(form-init3270266102980636870.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException, compiling:(html.clj:63:1)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:430)
	at clojure.lang.Compiler.eval(Compiler.java:6708)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.loadResourceScript(RT.java:361)
	at clojure.lang.RT.load(RT.java:440)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at codox.main$writer$fn__571.invoke(main.clj:11)
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at clojure.lang.Compiler$NewExpr.eval(Compiler.java:2484)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:417)
	... 37 more
Caused by: java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:94)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:73)
	... 43 more
Subprocess failed
```

**Comment by weavejester** [comment]
The `lein-codox` package adds the `codox` package to the project dependencies, so if you add the dependency in manually you can use `lein deps :tree` to check the dependencies.

In this case it's likely to do with sirthias/pegdown#66. It looks like Hadoop pulls in an ASM dependencies that conflicts with the one used by Pegdown.

**Comment by mbossenbroek** [comment]
Thanks for the pointer - I just excluded asm from the hadoop dependency & it works fine now. Thanks!

`[org.apache.hadoop/hadoop-core "1.1.2" :exclusions [asm]]`
