### ISSUE TITLE
Codox fail when using lein managed dependencies

### ISSUE THREAD

**Issue by 0xbase12** [weavejester/codox#166]
```
Exception in thread "main" java.lang.AssertionError: Assert failed: (dep-spec? dep-spec)
        at leinjacker.deps$dep_name.invokeStatic(deps.clj:23)
        at leinjacker.deps$dep_name.invoke(deps.clj:23)
        at leinjacker.deps$has_dep_QMARK_$fn__841.invoke(deps.clj:41)
        at clojure.core$some.invokeStatic(core.clj:2592)
        at clojure.core$some.invoke(core.clj:2583)
        at leinjacker.deps$has_dep_QMARK_.invokeStatic(deps.clj:41)
        at leinjacker.deps$has_dep_QMARK_.invoke(deps.clj:30)
        at leinjacker.deps$add_if_missing.invokeStatic(deps.clj:50)
        at leinjacker.deps$add_if_missing.invoke(deps.clj:43)
```
This exception is due to leinjacker which doesn't support managed dependencies. 
The last snapshot version has a fix for this issue:
https://github.com/sattvik/leinjacker/commit/3f4b0d73170dcd984608c703d80ee4d52dcdac73

**Comment by MatthewDarling** [comment]
I mentioned over on sattvik/leinjacker#14, but there's `[kirasystems/leinjacker "0.4.3"]` that includes the latest code and could be used. Alternatively, `[kirasystems/lein-codox "0.10.4"]` includes that version and doesn't have any other changes.

In fact, the main library code is unchanged, so the plugin [uses the latest official `codox` library](https://github.com/kirasystems/codox/blob/master/lein-codox/src/leiningen/codox.clj#L28) rather than a forked version :)

**Comment by AndreTheHunter** [comment]
@weavejester when will this fix be deployed?

**Comment by weavejester** [comment]
0.10.7 has been released. Sorry about the delay - it slipped off my todo list.
