### ISSUE TITLE
Document how to use with deps.edn

### ISSUE THREAD

**Issue by metasoarous** [weavejester/codox#194]
Hello

I'm considering using codox to document [Oz](https://github.com/metasoarous/oz) & [Semantic CSV](https://github.com/metasoarous/semantic-csv), but Oz uses `clj` & `deps.edn`, and I will be moving Semantic CSV to the same. I see from #163 that `codox` doesn't require leiningen, but I don't see any documentation about how I might use it with the `deps.edn` toolchain.

It seems like I can just manually call `codox.main/generate-docs`, likely even from a `deps.edn` alias, but it would be nice to see some examples of this.

Thanks!

**Comment by metasoarous** [comment]
I tried doing this using the new `-X` option, with an alias like so:

```
{...
 :aliases {
           :docs {:extra-deps {codox/codox {:mvn/version "0.10.7"}}
                  :exec-fn codox.main/generate-docs
                  :exec-args {:language :clojure
                              :output-path "docs"}}
           ...}}
```

In theory, this should be a pretty good option for doing this. However, I get the following:

```
% clj -A:clojupyter -X:docs                                                               :( 1 20-11-22 - 0:47:47
Exception in thread "main" java.lang.Exception: Could not load codox writer codox.writer.html
        at codox.main$writer$fn__816.invoke(main.clj:16)
        at codox.main$writer.invokeStatic(main.clj:12)
        at codox.main$writer.invoke(main.clj:9)
        at codox.main$generate_docs.invokeStatic(main.clj:122)
        at codox.main$generate_docs.invoke(main.clj:116)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at clojure.run.exec$exec.invokeStatic(exec.clj:37)
        at clojure.run.exec$exec.doInvoke(exec.clj:32)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at clojure.run.exec$_main.invokeStatic(exec.clj:147)
        at clojure.run.exec$_main.doInvoke(exec.clj:137)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:491)
        at clojure.main$main_opt.invoke(main.clj:487)
        at clojure.main$main.invokeStatic(main.clj:598)
        at clojure.main$main.doInvoke(main.clj:561)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:37)
Caused by: Syntax error compiling at (hiccup/page.clj:10:4).
        at clojure.lang.Compiler.analyze(Compiler.java:6808)
        at clojure.lang.Compiler.analyze(Compiler.java:6745)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3820)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7108)
        at clojure.lang.Compiler.analyze(Compiler.java:6789)
        at clojure.lang.Compiler.analyze(Compiler.java:6745)
        at clojure.lang.Compiler$MapExpr.parse(Compiler.java:3104)
        at clojure.lang.Compiler.analyze(Compiler.java:6797)
        at clojure.lang.Compiler.access$300(Compiler.java:38)
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:596)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
        at clojure.lang.Compiler.analyze(Compiler.java:6789)
        at clojure.lang.Compiler.analyze(Compiler.java:6745)
        at clojure.lang.Compiler.eval(Compiler.java:7180)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:463)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.core$load$fn__6824.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5989)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$use.invokeStatic(core.clj:6093)
        at clojure.core$use.doInvoke(core.clj:6093)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at codox.writer.html$eval914$loading__6706__auto____915.invoke(html.clj:1)
        at codox.writer.html$eval914.invokeStatic(html.clj:1)
        at codox.writer.html$eval914.invoke(html.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7176)
        at clojure.lang.Compiler.eval(Compiler.java:7165)
        at clojure.lang.Compiler.load(Compiler.java:7635)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:463)
        at clojure.lang.RT.load(RT.java:428)
        at clojure.core$load$fn__6824.invoke(core.clj:6126)
        at clojure.core$load.invokeStatic(core.clj:6125)
        at clojure.core$load.doInvoke(core.clj:6109)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5908)
        at clojure.core$load_one.invoke(core.clj:5903)
        at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
        at clojure.core$load_lib.invokeStatic(core.clj:5947)
        at clojure.core$load_lib.doInvoke(core.clj:5928)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$load_libs.invokeStatic(core.clj:5985)
        at clojure.core$load_libs.doInvoke(core.clj:5969)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$require.invokeStatic(core.clj:6007)
        at clojure.core$require.doInvoke(core.clj:6007)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at codox.main$writer$fn__816.invoke(main.clj:13)
        ... 24 more
Caused by: java.lang.RuntimeException: No such var: util/raw-string
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler.resolveIn(Compiler.java:7387)
        at clojure.lang.Compiler.resolve(Compiler.java:7357)
        at clojure.lang.Compiler.analyzeSymbol(Compiler.java:7318)
        at clojure.lang.Compiler.analyze(Compiler.java:6768)
        ... 89 more
```

(Note that I'm adding `-A:clojupyter` so that certain optional namespace can be loaded properly).

Any idea what might be going on here?

thanks

**Comment by weavejester** [comment]
It looks like you have a strange dependency issue with Hiccup, where the hiccup.page namespace is from 2.0, and the hiccup.util namespace is from 1.0. Try wiping the class files in your target directory.

**Comment by metasoarous** [comment]
Hi @weavejester. Thanks for the rapid response!

I will note that Oz is using hiccup `2.0.0-alpha2`. Seems like that could explain the issue? But then strange that it's required without issue from the REPL. I did try nuking my `target` directory to no avail.

Is hiccup getting close to a non-alpha 2.0.0 readiness? Would it be feasible to update this dependency for codox?

Thanks again!

**Comment by weavejester** [comment]
Something seems strange in your build chain if you're ending up with compiled namespaces from two different versions of the same dependency.

Hiccup 2.0 is backward compatible with 1.0, so you could just manually force Codox to use Hiccup 2.0.

**Comment by metasoarous** [comment]
Thanks again for the quick response.

The problem here appears to be an issue with Clojupyter AOT/Uberjar compiling with an older version of hiccup. If I comment out the namespace which uses Clojupyter and leave `clojupyter` out of the list of dependencies, compilation works fine.

I'll submit a PR for an update to the README that documents how to use codox with `deps.edn`.

Thanks again!
