### ISSUE TITLE
Error trying to use src-dir-uri 

### ISSUE THREAD

**Issue by kilkerran** [weavejester/codox#75]
Setting  :codox {:src-dir-uri "http://myStashUrl/projects/FXO/repos/xm/browse/xcore/"}  and getting a failure on the doc run. Looks like the URI parser is getting forward slashes added as it runs through the files? I'm on a windows machine..............

   at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.net.URISyntaxException: Illegal character in path at index 67: http://myStashUrl/projects/FXO/repos/xm/browse/xcore/dev\dev.clj
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parseHierarchical(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at hiccup.util$eval412$fn__413.invoke(util.clj:49)

**Comment by MIvanchev** [comment]
Confirmed on Windows 7.

**Comment by weavejester** [comment]
@kilkerran, @MIvanchev, could either of you test Codox 0.8.11-SNAPSHOT and see if that works for you?
