### ISSUE TITLE
Codox has suddenly stopped working

### ISSUE THREAD

**Issue by brunchboy** [weavejester/codox#94]
When I try, it crashes thus:

```
Exception in thread "main" java.lang.Exception: Could not load codox writer codox.writer.html, compiling:(/private/var/folders/fg/1tzg0xt88v5bp20059blypr00000gq/T/form-init2205342660127933571.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7249)
	at clojure.lang.Compiler.loadFile(Compiler.java:7175)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Could not load codox writer codox.writer.html
	at codox.main$writer$fn__231.invoke(main.clj:13)
	at codox.main$writer.invoke(main.clj:9)
	at codox.main$generate_docs.invoke(main.clj:74)
	at user$eval295.invoke(form-init2205342660127933571.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6792)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7237)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException, compiling:(html.clj:30:1)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:452)
	at clojure.lang.Compiler.eval(Compiler.java:6797)
	at clojure.lang.Compiler.load(Compiler.java:7237)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5446.invoke(core.clj:5862)
	at clojure.core$load.doInvoke(core.clj:5861)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5667)
	at clojure.core$load_lib$fn__5395.invoke(core.clj:5707)
	at clojure.core$load_lib.doInvoke(core.clj:5706)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$load_libs.doInvoke(core.clj:5745)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$require.doInvoke(core.clj:5828)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at codox.main$writer$fn__231.invoke(main.clj:10)
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at clojure.lang.Compiler$NewExpr.eval(Compiler.java:2553)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:439)
	... 37 more
Caused by: java.lang.IncompatibleClassChangeError: class org.objectweb.asm.tree.ClassNode has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:71)
	... 43 more
Subprocess failed
```

**Comment by weavejester** [comment]
Have you tried running `lein clean`?

**Comment by weavejester** [comment]
Another possible cause of your issue is incompatible Pegdown versions in your dependency tree. Check it with `lein deps :tree`.

**Comment by brunchboy** [comment]
Indeed, I tried both of those things before posting this, alas. When I run `lein deps :tree` I do see a couple of conflicting dependencies, but nothing at all refers to codox or Pegdown, as far as I can see:

```
Possibly confusing dependencies found:
[cider/cider-nrepl "0.8.2"] -> [org.clojure/java.classpath "0.2.0" :exclusions [org.clojure/clojure]]
 overrides
[metosin/ring-middleware-format "0.6.0"] -> [ring "1.3.2"] -> [ring/ring-devel "1.3.2"] -> [ns-tracker "0.2.2"] -> [org.clojure/java.classpath "0.2.2"]
 and
[ring/ring-devel "1.3.2"] -> [ns-tracker "0.2.2"] -> [org.clojure/java.classpath "0.2.2"]

Consider using these exclusions:
[metosin/ring-middleware-format "0.6.0" :exclusions [org.clojure/java.classpath]]
[ring/ring-devel "1.3.2" :exclusions [org.clojure/java.classpath]]

 [amalloy/ring-buffer "1.1"]
 [bouncer "0.3.3"]
   [clj-time "0.9.0"]
   [com.andrewmcveigh/cljs-time "0.3.0"]
     [com.cemerick/austin "0.1.5"]
       [com.cemerick/piggieback "0.1.3"]
     [org.clojure/clojurescript "0.0-2511"]
       [com.google.javascript/closure-compiler "v20140625"]
         [args4j "2.0.26"]
         [com.google.code.findbugs/jsr305 "1.3.9"]
         [com.google.guava/guava "17.0"]
         [com.google.javascript/closure-compiler-externs "v20140625"]
         [com.google.protobuf/protobuf-java "2.5.0"]
       [org.clojure/data.json "0.2.3"]
       [org.clojure/google-closure-library "0.0-20140718-946a7d39"]
         [org.clojure/google-closure-library-third-party "0.0-20140718-946a7d39"]
       [org.mozilla/rhino "1.7R4"]
 [buddy "0.5.4"]
   [buddy/buddy-auth "0.5.3"]
     [cuerdas "0.3.2"]
   [buddy/buddy-core "0.5.0"]
     [org.bouncycastle/bcpkix-jdk15on "1.52"]
     [org.bouncycastle/bcprov-jdk15on "1.52"]
   [buddy/buddy-hashers "0.4.2"]
     [clojurewerkz/scrypt "1.2.0"]
       [com.lambdaworks/scrypt "1.4.0"]
   [buddy/buddy-sign "0.5.1"]
     [cats "0.4.0"]
     [com.taoensso/nippy "2.8.0"]
       [net.jpountz.lz4/lz4 "1.3"]
       [org.iq80.snappy/snappy "0.3"]
       [org.tukaani/xz "1.5"]
 [cider/cider-nrepl "0.8.2"]
   [cljs-tooling "0.1.3" :exclusions [[org.clojure/clojure]]]
   [compliment "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/java.classpath "0.2.0" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.namespace "0.2.5" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.trace "0.7.8" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [com.climate/claypoole "1.0.0"]
 [com.taoensso/timbre "3.4.0"]
   [com.taoensso/encore "1.21.0"]
   [io.aviso/pretty "0.1.16"]
 [com.taoensso/tower "3.0.2"]
 [compojure "1.3.4"]
   [clout "2.1.2"]
   [medley "0.6.0"]
   [org.clojure/tools.macro "0.1.5"]
   [ring/ring-codec "1.0.0"]
   [ring/ring-core "1.3.2"]
     [commons-fileupload "1.3"]
     [commons-io "2.4"]
     [crypto-equality "1.0.0"]
     [crypto-random "1.2.0"]
 [environ "1.0.0"]
 [http-kit "2.1.19"]
 [instaparse "1.4.0"]
 [markdown-clj "0.9.66"]
 [metosin/ring-http-response "0.6.2"]
   [potemkin "0.3.13"]
     [clj-tuple "0.2.1"]
     [riddley "0.1.7"]
   [slingshot "0.12.2"]
 [metosin/ring-middleware-format "0.6.0"]
   [clj-yaml "0.4.0"]
     [org.yaml/snakeyaml "1.5"]
   [com.cognitect/transit-clj "0.8.269"]
     [com.cognitect/transit-java "0.8.276"]
       [com.fasterxml.jackson.datatype/jackson-datatype-json-org "2.3.2"]
         [com.fasterxml.jackson.core/jackson-databind "2.3.2"]
           [com.fasterxml.jackson.core/jackson-annotations "2.3.0"]
         [org.json/json "20090211"]
       [org.apache.directory.studio/org.apache.commons.codec "1.8"]
       [org.msgpack/msgpack "0.6.10"]
         [com.googlecode.json-simple/json-simple "1.1.1" :exclusions [[junit]]]
         [org.javassist/javassist "3.18.1-GA"]
   [com.ibm.icu/icu4j "54.1.1"]
   [org.clojure/core.memoize "0.5.7"]
   [org.clojure/tools.reader "0.8.15"]
   [ring "1.3.2"]
     [ring/ring-jetty-adapter "1.3.2"]
       [org.eclipse.jetty/jetty-server "7.6.13.v20130916"]
         [org.eclipse.jetty.orbit/javax.servlet "2.5.0.v201103041518"]
         [org.eclipse.jetty/jetty-continuation "7.6.13.v20130916"]
         [org.eclipse.jetty/jetty-http "7.6.13.v20130916"]
           [org.eclipse.jetty/jetty-io "7.6.13.v20130916"]
             [org.eclipse.jetty/jetty-util "7.6.13.v20130916"]
     [ring/ring-servlet "1.3.2"]
 [org.clojars.brunchboy/colors "1.0.2-20150516.165903-4"]
   [org.clojure/core.incubator "0.1.3"]
 [org.clojure/clojure "1.7.0-RC1"]
 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
   [org.clojure/tools.analyzer.jvm "0.1.0-beta12"]
     [org.clojure/tools.analyzer "0.1.0-beta12"]
     [org.ow2.asm/asm-all "4.1"]
 [org.clojure/core.cache "0.6.4"]
   [org.clojure/data.priority-map "0.0.4"]
 [org.clojure/math.numeric-tower "0.0.4"]
 [org.clojure/tools.cli "0.3.1"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.flatland/protobuf "0.8.1"]
   [ordered-collections "0.4.0"]
   [org.flatland/io "0.3.0"]
   [org.flatland/schematic "0.1.0"]
   [org.flatland/useful "0.9.0"]
 [overtone/at-at "1.2.0"]
 [overtone/midi-clj "0.5.0"]
 [prone "0.8.2"]
 [ring-mock "0.1.5" :scope "test"]
 [ring/ring-defaults "0.1.5"]
   [javax.servlet/servlet-api "2.5"]
   [ring/ring-anti-forgery "1.0.0"]
   [ring/ring-headers "0.1.3"]
   [ring/ring-ssl "0.2.1"]
 [ring/ring-devel "1.3.2" :scope "test"]
   [clj-stacktrace "0.2.7" :scope "test"]
   [hiccup "1.0.5"]
   [ns-tracker "0.2.2" :scope "test"]
 [ring/ring-session-timeout "0.1.0"]
 [ritz/ritz-nrepl-middleware "0.7.0"]
   [ritz/ritz-repl-utils "0.7.0"]
 [selmer "0.8.2"]
   [cheshire "5.4.0"]
     [com.fasterxml.jackson.core/jackson-core "2.4.4"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.4.4"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.4.4"]
     [tigris "0.1.1"]
   [commons-codec "1.10"]
   [joda-time "2.7"]
 [slamhound "1.5.5"]
```

**Comment by brunchboy** [comment]
And indeed, after trying the suggested exclusions just now, I get a clean report from `lein deps :tree` but the same failure trying to run `lein doc`.

**Comment by brunchboy** [comment]
In the event you want to try to reproduce this, my project is [Afterglow](https://github.com/brunchboy/afterglow).

**Comment by brunchboy** [comment]
Oh, wow, this is happening to me on a *much* simpler project too, with just one dependency (clojure 1.6) and one plugin (codox). That should help narrow it down? It is my [matcha fork](https://github.com/brunchboy/matcha)

**Comment by brunchboy** [comment]
Ok, I figured out the source of the conflict. It was the presence of a Java [Extension](https://github.com/brunchboy/osxmidi4j) to make MIDI work properly in Java on the Mac (enable SysEx messages and live plugging of devices). I am closing this because codox works without that, and I will see what I can do to get rid of the conflict. In the mean time I can disable the extension when I am not actually running light shows. Sorry about the false alarm!

**Comment by weavejester** [comment]
No problem. A Java extension is a pretty obscure source for a bug like this.

**Comment by brunchboy** [comment]
Indeed! It turns out, though, that osxmidi4j is a disaster to put in your Java Extensions directory. It embeds way too many classes and frameworks and thereby is just an incompatibility crash waiting to happen. Sadly, I can’t fix that since some of the big problem frameworks (including asm, cglib, log4j, and sl4j) are used by its basic JNA approach to talk to native Objective C code (rococoa, another project which seems abandoned). So I am back to square one. There is another implementation of a solution to the underlying bad MIDI implementation issue, [mmj](http://www.humatic.de/htools/mmj.htm), but the creators retired it in 2010, and it is not open source so I can’t try to fix the live-plugging issue like I did with osxmidi4j. I have sent the company a plea to release the source code as open source, but if they don’t decide to, it looks like I will have a side project of writing a bunch of tedious JNI code to reimplement it someday.
